services:
  gfpgan:
    image: gfpgan_inference
    container_name: gfpgan
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/poc4a5000/detect/detect/faces:/app/GFPGAN/faces
    ports:
      - "8005:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0", "1", "2", "3"]
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - FOLDER_PATH=/app/GFPGAN/faces
      - MOUNT_PATH=/home/poc4a5000/detect/detect/faces
