services:
  gfpgan:
    image: gfpgan_inference
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./images:/app/GFPGAN/images
      - ./outputs:/app/GFPGAN/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0', '1','2','3' ]
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
